name: Actions-WorkFlow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: "John"
      - name: Capture TimeStamp of greet
        run: echo "{{ steps.greet.outputs.time }}"
