name: Print Environment Variables - workflow

on: [push]

env:
  WF_ENV: Available to All Jobs in WorkFlow

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to All steps in this Job
    steps:
      - name: Step 1
        env:
          STEP_ENV: Available in this step only
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Step 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_EV: ${STEP_ENV}"
      - name: Step 3 - Print Default Environment Variables
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_PATH: ${GITHUB_PATH}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_ENV: ${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "RUNNER_NAME: ${RUNNER_NAME}"
          echo "RUNNER_OS: ${RUNNER_OS}"
          